name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: xabush/annotation-scheme:latest
    steps:
      - uses: actions/checkout@v2

      - name: Compiling
        run: autoreconf -vif && ./configure GUILE=$(which guile) && make 

      - name: Running Tests
        run: make check
